name: "GCS Test Report Upload Action"
description: "An opinionated GitHub composite action to upload HTML test reports to a GCS bucket and website"
author: "Bruno Paz"
branding:
  icon: "upload-cloud"
  color: "blue"
inputs:
  gcp_project_id:
    description: "The Google Cloud project ID"
    required: true
  gcp_workload_identity_provider:
    description: "The Google Cloud Workload Identity provider"
    required: false
  gcp_credentials:
    description: "The Google Cloud credentials"
    required: false
  gcs_bucket_name:
    description: "The GCS bucket where to upload reports."
    required: false
    default: "test-reports.brunopaz.xyz"
  gcs_bucket_public_url:
    description: "The public URL of the GCS bucket."
    required: false
    default: "https://test-reports.brunopaz.xyz"
  report_name:
    description: "A identifiable name for the report. Will be used in the action outputs."
    required: false
    default: "Test results"
  report_folder:
    description: "The folder where the report is stored."
    required: true
  pull_request_check:
    description: "Whether to create a PR check with the report URL."
    required: false
    default: "true"
  generate_summary:
    description: "Whether to generate a summary with the report URL."
    required: false
    default: "true"
  github-token:
    description: "The GitHub token to create the PR check."
    required: false

outputs:
  report_url:
    description: "Public URL for the report"
    value: ${{ steps.output-report-url.outputs.url }}
runs:
  using: "composite"
  steps:
    - name: Report Upload | Authenticate in Google Cloud
      uses: "google-github-actions/auth@v2"
      with:
        project_id: ${{ inputs.gcp_project_id }}
        workload_identity_provider: "${{ inputs.gcp_workload_identity_provider }}"
        credentials_json: "${{ inputs.gcp_credentials }}"

    - name: Report Upload | Set destination path
      shell: bash
      id: "set-destination-path"
      run: |
        BASENAME_REPORT_FOLDER=$(basename "${{ inputs.report_folder }}")
        REPORT_GCS_PATH=${{ github.repository }}/${{ github.run_id }}
        REPORT_GCS_FULL_PATH="${{ inputs.gcs_bucket_name }}/${REPORT_GCS_PATH}"
        REPORT_PUBLIC_URL="${{ inputs.gcs_bucket_public_url }}/${REPORT_GCS_PATH}/${BASENAME_REPORT_FOLDER}"

        echo "destination_path=${REPORT_GCS_FULL_PATH}" >> $GITHUB_ENV
        echo "report_public_url=${REPORT_PUBLIC_URL}" >> $GITHUB_ENV

    - name: Report Upload | Upload report to GCS bucket
      uses: "google-github-actions/upload-cloud-storage@v2"
      with:
        path: ${{ inputs.report_folder }}
        destination: ${{ env.destination_path }}
        process_gcloudignore: "false"

    - name: Report Upload | Generate summary
      shell: bash
      if: ${{ inputs.generate_summary == 'true' }}
      run: |
        echo "## ${{ inputs.report_name }}" >> "$GITHUB_STEP_SUMMARY"
        echo "${{ env.report_public_url }}" >> "$GITHUB_STEP_SUMMARY"

    - name: Report Upload | Generate PR check
      if: ${{ inputs.pull_request_check == 'true' }} && ${{ github.event_name == 'pull_request' }}
      uses: patriknyblad/add-pr-checks@v1.1.0
      with:
        token: ${{ inputs.github-token }}
        checks: |
          - name: ${{ inputs.report_name }} Test Report
            value: ${{ env.report_public_url }}
            summary: "Test report available at: ${{ env.report_public_url }}"
            text: |
              Report URL available at: ${{ env.report_public_url }}

    - name: Report Upload | Output report URL
      shell: bash
      id: "output-report-url"
      run: |
        echo "url=$REPORT_PUBLIC_URL" >> $GITHUB_OUTPUT
